package com.itek.myoa.domain;

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author Administrator
 * @date 2019-07-09
 */
public class ApplicationLeave implements Serializable {
    public ApplicationLeave() {
    }

    public ApplicationLeave(Integer applyerId, String applyerName, String startTime, String endTime, String reson) {
        this.applyerId = applyerId;
        this.applyerName = applyerName;
        this.reson = reson;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        try {
            this.startTime = sdf.parse(startTime);
            this.endTime = sdf.parse(endTime);
        } catch (ParseException e) {
            e.printStackTrace();
        }

    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_leave.id
     *
     * @mbggenerated
     */
    /**
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_leave.applyer_name
     *
     * @mbggenerated
     */
    /**
     *
     */
    private String applyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_leave.applyer_id
     *
     * @mbggenerated
     */
    /**
     *
     */
    private Integer applyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_leave.start_time
     *
     * @mbggenerated
     */
    /**
     *
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_leave.end_time
     *
     * @mbggenerated
     */
    /**
     *
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_leave.reson
     *
     * @mbggenerated
     */
    /**
     *
     */
    private String reson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_leave.status
     *
     * @mbggenerated
     */
    /**
     * 0-正在审批，1-审批通过，2-审批未通过
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_leave.approval_role_id
     *
     * @mbggenerated
     */
    /**
     *
     */
    private String approvalRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_leave.id
     *
     * @return the value of t_application_leave.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_leave.id
     *
     * @param id the value for t_application_leave.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_leave.applyer_name
     *
     * @return the value of t_application_leave.applyer_name
     * @mbggenerated
     */
    public String getApplyerName() {
        return applyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_leave.applyer_name
     *
     * @param applyerName the value for t_application_leave.applyer_name
     * @mbggenerated
     */
    public void setApplyerName(String applyerName) {
        this.applyerName = applyerName == null ? null : applyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_leave.applyer_id
     *
     * @return the value of t_application_leave.applyer_id
     * @mbggenerated
     */
    public Integer getApplyerId() {
        return applyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_leave.applyer_id
     *
     * @param applyerId the value for t_application_leave.applyer_id
     * @mbggenerated
     */
    public void setApplyerId(Integer applyerId) {
        this.applyerId = applyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_leave.start_time
     *
     * @return the value of t_application_leave.start_time
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_leave.start_time
     *
     * @param startTime the value for t_application_leave.start_time
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_leave.end_time
     *
     * @return the value of t_application_leave.end_time
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_leave.end_time
     *
     * @param endTime the value for t_application_leave.end_time
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_leave.reson
     *
     * @return the value of t_application_leave.reson
     * @mbggenerated
     */
    public String getReson() {
        return reson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_leave.reson
     *
     * @param reson the value for t_application_leave.reson
     * @mbggenerated
     */
    public void setReson(String reson) {
        this.reson = reson == null ? null : reson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_leave.status
     *
     * @return the value of t_application_leave.status
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_leave.status
     *
     * @param status the value for t_application_leave.status
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_leave.approval_role_id
     *
     * @return the value of t_application_leave.approval_role_id
     * @mbggenerated
     */
    public String getApprovalRoleId() {
        return approvalRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_leave.approval_role_id
     *
     * @param approvalRoleId the value for t_application_leave.approval_role_id
     * @mbggenerated
     */
    public void setApprovalRoleId(String approvalRoleId) {
        this.approvalRoleId = approvalRoleId == null ? null : approvalRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApplicationLeave other = (ApplicationLeave) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getApplyerName() == null ? other.getApplyerName() == null : this.getApplyerName().equals(other.getApplyerName()))
                && (this.getApplyerId() == null ? other.getApplyerId() == null : this.getApplyerId().equals(other.getApplyerId()))
                && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
                && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
                && (this.getReson() == null ? other.getReson() == null : this.getReson().equals(other.getReson()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getApprovalRoleId() == null ? other.getApprovalRoleId() == null : this.getApprovalRoleId().equals(other.getApprovalRoleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getApplyerName() == null) ? 0 : getApplyerName().hashCode());
        result = prime * result + ((getApplyerId() == null) ? 0 : getApplyerId().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getReson() == null) ? 0 : getReson().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getApprovalRoleId() == null) ? 0 : getApprovalRoleId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", applyerName=").append(applyerName);
        sb.append(", applyerId=").append(applyerId);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", reson=").append(reson);
        sb.append(", status=").append(status);
        sb.append(", approvalRoleId=").append(approvalRoleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}