package com.itek.myoa.domain;

import java.io.Serializable;

/**
 * 
 *
 * @author Administrator
 * @date 2019-07-09
 *
 */
public class ApprovalProcess implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_process.id
     *
     * @mbggenerated
     */
    /**  */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_process.approval_name
     *
     * @mbggenerated
     */
    /** 审批名称 */
    private String approvalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_approval_process.approval_role_list
     *
     * @mbggenerated
     */
    /** 审批流程角色列表 */
    private String approvalRoleList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_process.id
     *
     * @return the value of t_approval_process.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_process.id
     *
     * @param id the value for t_approval_process.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_process.approval_name
     *
     * @return the value of t_approval_process.approval_name
     *
     * @mbggenerated
     */
    public String getApprovalName() {
        return approvalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_process.approval_name
     *
     * @param approvalName the value for t_approval_process.approval_name
     *
     * @mbggenerated
     */
    public void setApprovalName(String approvalName) {
        this.approvalName = approvalName == null ? null : approvalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_approval_process.approval_role_list
     *
     * @return the value of t_approval_process.approval_role_list
     *
     * @mbggenerated
     */
    public String getApprovalRoleList() {
        return approvalRoleList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_approval_process.approval_role_list
     *
     * @param approvalRoleList the value for t_approval_process.approval_role_list
     *
     * @mbggenerated
     */
    public void setApprovalRoleList(String approvalRoleList) {
        this.approvalRoleList = approvalRoleList == null ? null : approvalRoleList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApprovalProcess other = (ApprovalProcess) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getApprovalName() == null ? other.getApprovalName() == null : this.getApprovalName().equals(other.getApprovalName()))
            && (this.getApprovalRoleList() == null ? other.getApprovalRoleList() == null : this.getApprovalRoleList().equals(other.getApprovalRoleList()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getApprovalName() == null) ? 0 : getApprovalName().hashCode());
        result = prime * result + ((getApprovalRoleList() == null) ? 0 : getApprovalRoleList().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", approvalName=").append(approvalName);
        sb.append(", approvalRoleList=").append(approvalRoleList);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}