package com.itek.myoa.domain;

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * 
 *
 * @author Administrator
 * @date 2019-07-12
 *
 */
public class ZCApplication implements Serializable {
    public ZCApplication(){}

    public ZCApplication(Integer id,
                         Integer applyerId,
                         String applyerName,
                         String applyTime,
                         String status,
                         Integer approvalRoleId,
                         String resonShopping,
                         String proName,
                         Integer proNumber,
                         Double proPrice,
                         String tip) {
        this.id = id;
        this.applyerId = applyerId;
        this.applyerName = applyerName;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        try {
            this.applyTime = sdf.parse(applyTime);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        this.status = status;
        this.approvalRoleId = approvalRoleId;
        this.resonShopping = resonShopping;
        this.proName = proName;
        this.proNumber = proNumber;
        this.proPrice = proPrice;
        this.tip = tip;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.id
     *
     * @mbggenerated
     */
    /** 资产申请记录id */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.applyer_id
     *
     * @mbggenerated
     */
    /** 申请人id */
    private Integer applyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.applyer_name
     *
     * @mbggenerated
     */
    /** 申请人姓名 */
    private String applyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.apply_time
     *
     * @mbggenerated
     */
    /** 申请时间 */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.status
     *
     * @mbggenerated
     */
    /** 0 正在审核  1 审核通过 2 审核未通过 */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.approval_role_id
     *
     * @mbggenerated
     */
    /** 交于角色id为此字段的人审批 */
    private Integer approvalRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.reson_shopping
     *
     * @mbggenerated
     */
    /** 采购原因说明 */
    private String resonShopping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.pro_name
     *
     * @mbggenerated
     */
    /** 采购产品名字 */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.pro_number
     *
     * @mbggenerated
     */
    /** 采购数量 */
    private Integer proNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.pro_price
     *
     * @mbggenerated
     */
    /** 采购单价 */
    private Double proPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_application_zc.tip
     *
     * @mbggenerated
     */
    /** 备注 */
    private String tip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.id
     *
     * @return the value of t_application_zc.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.id
     *
     * @param id the value for t_application_zc.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.applyer_id
     *
     * @return the value of t_application_zc.applyer_id
     *
     * @mbggenerated
     */
    public Integer getApplyerId() {
        return applyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.applyer_id
     *
     * @param applyerId the value for t_application_zc.applyer_id
     *
     * @mbggenerated
     */
    public void setApplyerId(Integer applyerId) {
        this.applyerId = applyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.applyer_name
     *
     * @return the value of t_application_zc.applyer_name
     *
     * @mbggenerated
     */
    public String getApplyerName() {
        return applyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.applyer_name
     *
     * @param applyerName the value for t_application_zc.applyer_name
     *
     * @mbggenerated
     */
    public void setApplyerName(String applyerName) {
        this.applyerName = applyerName == null ? null : applyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.apply_time
     *
     * @return the value of t_application_zc.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.apply_time
     *
     * @param applyTime the value for t_application_zc.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.status
     *
     * @return the value of t_application_zc.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.status
     *
     * @param status the value for t_application_zc.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.approval_role_id
     *
     * @return the value of t_application_zc.approval_role_id
     *
     * @mbggenerated
     */
    public Integer getApprovalRoleId() {
        return approvalRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.approval_role_id
     *
     * @param approvalRoleId the value for t_application_zc.approval_role_id
     *
     * @mbggenerated
     */
    public void setApprovalRoleId(Integer approvalRoleId) {
        this.approvalRoleId = approvalRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.reson_shopping
     *
     * @return the value of t_application_zc.reson_shopping
     *
     * @mbggenerated
     */
    public String getResonShopping() {
        return resonShopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.reson_shopping
     *
     * @param resonShopping the value for t_application_zc.reson_shopping
     *
     * @mbggenerated
     */
    public void setResonShopping(String resonShopping) {
        this.resonShopping = resonShopping == null ? null : resonShopping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.pro_name
     *
     * @return the value of t_application_zc.pro_name
     *
     * @mbggenerated
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.pro_name
     *
     * @param proName the value for t_application_zc.pro_name
     *
     * @mbggenerated
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.pro_number
     *
     * @return the value of t_application_zc.pro_number
     *
     * @mbggenerated
     */
    public Integer getProNumber() {
        return proNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.pro_number
     *
     * @param proNumber the value for t_application_zc.pro_number
     *
     * @mbggenerated
     */
    public void setProNumber(Integer proNumber) {
        this.proNumber = proNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.pro_price
     *
     * @return the value of t_application_zc.pro_price
     *
     * @mbggenerated
     */
    public Double getProPrice() {
        return proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.pro_price
     *
     * @param proPrice the value for t_application_zc.pro_price
     *
     * @mbggenerated
     */
    public void setProPrice(Double proPrice) {
        this.proPrice = proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_application_zc.tip
     *
     * @return the value of t_application_zc.tip
     *
     * @mbggenerated
     */
    public String getTip() {
        return tip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_application_zc.tip
     *
     * @param tip the value for t_application_zc.tip
     *
     * @mbggenerated
     */
    public void setTip(String tip) {
        this.tip = tip == null ? null : tip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ZCApplication other = (ZCApplication) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getApplyerId() == null ? other.getApplyerId() == null : this.getApplyerId().equals(other.getApplyerId()))
            && (this.getApplyerName() == null ? other.getApplyerName() == null : this.getApplyerName().equals(other.getApplyerName()))
            && (this.getApplyTime() == null ? other.getApplyTime() == null : this.getApplyTime().equals(other.getApplyTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getApprovalRoleId() == null ? other.getApprovalRoleId() == null : this.getApprovalRoleId().equals(other.getApprovalRoleId()))
            && (this.getResonShopping() == null ? other.getResonShopping() == null : this.getResonShopping().equals(other.getResonShopping()))
            && (this.getProName() == null ? other.getProName() == null : this.getProName().equals(other.getProName()))
            && (this.getProNumber() == null ? other.getProNumber() == null : this.getProNumber().equals(other.getProNumber()))
            && (this.getProPrice() == null ? other.getProPrice() == null : this.getProPrice().equals(other.getProPrice()))
            && (this.getTip() == null ? other.getTip() == null : this.getTip().equals(other.getTip()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getApplyerId() == null) ? 0 : getApplyerId().hashCode());
        result = prime * result + ((getApplyerName() == null) ? 0 : getApplyerName().hashCode());
        result = prime * result + ((getApplyTime() == null) ? 0 : getApplyTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getApprovalRoleId() == null) ? 0 : getApprovalRoleId().hashCode());
        result = prime * result + ((getResonShopping() == null) ? 0 : getResonShopping().hashCode());
        result = prime * result + ((getProName() == null) ? 0 : getProName().hashCode());
        result = prime * result + ((getProNumber() == null) ? 0 : getProNumber().hashCode());
        result = prime * result + ((getProPrice() == null) ? 0 : getProPrice().hashCode());
        result = prime * result + ((getTip() == null) ? 0 : getTip().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", applyerId=").append(applyerId);
        sb.append(", applyerName=").append(applyerName);
        sb.append(", applyTime=").append(applyTime);
        sb.append(", status=").append(status);
        sb.append(", approvalRoleId=").append(approvalRoleId);
        sb.append(", resonShopping=").append(resonShopping);
        sb.append(", proName=").append(proName);
        sb.append(", proNumber=").append(proNumber);
        sb.append(", proPrice=").append(proPrice);
        sb.append(", tip=").append(tip);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}