package com.itek.myoa.dao;

import com.itek.myoa.domain.ApplicationLeave;
import com.itek.myoa.domain.ApplicationLeaveExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ApplicationLeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    int countByExample(ApplicationLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    int deleteByExample(ApplicationLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    int insert(ApplicationLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    int insertSelective(ApplicationLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    List<ApplicationLeave> selectByExample(ApplicationLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    ApplicationLeave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApplicationLeave record, @Param("example") ApplicationLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApplicationLeave record, @Param("example") ApplicationLeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApplicationLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApplicationLeave record);

    int updateStatus(Integer applicationId);

    int updateApprovalRoleIdByapplicationId(Map<String, Object> map);

    int updateStatus2(Integer applicationId);
}