package com.itek.myoa.dao;

import com.itek.myoa.domain.ApprovalProcess;
import com.itek.myoa.domain.ApprovalProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApprovalProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    int countByExample(ApprovalProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    int deleteByExample(ApprovalProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    int insert(ApprovalProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    int insertSelective(ApprovalProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    List<ApprovalProcess> selectByExample(ApprovalProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    ApprovalProcess selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApprovalProcess record, @Param("example") ApprovalProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApprovalProcess record, @Param("example") ApprovalProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApprovalProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApprovalProcess record);
}