package com.itek.myoa.dao;

import com.itek.myoa.domain.Approval;
import com.itek.myoa.domain.ApprovalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApprovalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    int countByExample(ApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    int deleteByExample(ApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    int insert(Approval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    int insertSelective(Approval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    List<Approval> selectByExample(ApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    Approval selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Approval record, @Param("example") ApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Approval record, @Param("example") ApprovalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Approval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_approval
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Approval record);

    List<Approval> selectByTables();

    List<Approval> getZcApproval(Integer userId);

}