package com.itek.myoa.dao;

import com.itek.myoa.domain.ZCApplication;
import com.itek.myoa.domain.ZCApplicationExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ZCApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    int countByExample(ZCApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    int deleteByExample(ZCApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    int insert(ZCApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    int insertSelective(ZCApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    List<ZCApplication> selectByExample(ZCApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    ZCApplication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZCApplication record, @Param("example") ZCApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZCApplication record, @Param("example") ZCApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZCApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_application_zc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZCApplication record);

    int updateById(Integer applicationId);

    int updateById2(Integer applicationId);

    int updateNewRoleIdByApplicationIdAndNewRoleId(Map<String, Object> map);
}